require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  SpecSuffixOnly: true

Metrics/BlockLength:
 Exclude:
  - './spec/**/*'
AllCops:
  NewCops: enable
  Exclude:
    - './bin/bundle'