name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  rspec:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
    
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Migrations
        run: bundle exec rails db:create db:migrate RAILS_ENV=test

      - name: Run Rspec
        run: bundle exec rspec
